const SLOT_LABELS = { weapon: "Weapon", body: "Body", offhand: "Offhand", trinket: "Trinket" };
const RARITY_ORDER = ["Common", "Uncommon", "Rare", "Epic", "Legendary"];
const ARMOR_BASES = ["Body Bag Liner", "Sponsor-Approved Vest", "Stain-Hiding Jacket", "Crawler Onesie", "Regrettable Chest Plate"];
const OFFHAND_BASES = ["Complaint Shield", "Trash Can Lid", "Foam Finger", "Waiver Clipboard", "Door Prize Buckler"];
const TRINKET_BASES = ["Participation Charm", "Subscriber Badge", "Tiny Legal Waiver", "Applause Meter", "Questionable Token"];
const JUNK_BASES = ["Goblin Coupon", "Mostly Clean Sock", "Audience Survey Stub", "Expired Heal-ish Packet", "Signed Rat Headshot", "Dungeon-Branded Napkin"];
const ITEM_PREFIXES = ["Moldy", "Sponsored", "Litigation-Grade", "Applause-Hungry", "Questionable", "Premium", "Barely Legal", "Crowd-Tested", "Intern-Certified", "Dramatically Damp"];
const FLAVOR_LINES = [
  "Generated by the dungeon for your humiliation and eventual monetization.",
  "The audience likes this. They have been wrong before.",
  "A producer circled this item and wrote 'probably content'.",
  "Legally distinct from useful, but emotionally adjacent.",
  "The dungeon insists this is loot, not evidence."
];
const ROOM_NAMES = { small: ["Crypt Nook", "Goblin Pantry", "Collapsed Alcove", "Rat Nest", "Old Guard Room"], medium: ["Bone Gallery", "Broken Armory", "Forgotten Shrine", "Goblin Barracks", "Hall of Echoes", "Mushroom Chapel"], large: ["Feast Hall", "The Drowned Hall", "Cavern of Teeth", "Hall of Rusted Banners"], boss: ["The Rat King's Court", "The Bone Collector's Pit", "Champion's Den", "The Blood-Marked Chamber", "The Old Arena"] };
let selectedInventoryItemId = null;
let activeLootCorpseId = null;

function makeId(p = "item") { return `${p}_${Date.now()}_${Math.floor(Math.random() * 999999)}`; }
function choose(a) { return a[Math.floor(Math.random() * a.length)]; }
function rollRarity(force = false) { if (force) return Math.random() < 0.08 ? "Legendary" : "Rare"; const r = Math.random(); return r < 0.60 ? "Common" : r < 0.84 ? "Uncommon" : r < 0.96 ? "Rare" : r < 0.995 ? "Epic" : "Legendary"; }
function rarityPower(r) { return { Common: 1, Uncommon: 2, Rare: 3, Epic: 4, Legendary: 6 }[r] || 1; }
function escapeHtml(value) { return String(value ?? "").replace(/[&<>'"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[c])); }
function getItemStats(item) { return { hp: 0, attack: 0, defense: 0, speed: 0, audience: 0, damage: 0, range: 0, cooldown: 0, ...(item?.stats || {}) }; }
function isEquippable(item) { return item && ["weapon", "armor", "trinket"].includes(item.type) && item.slot; }

function createItem({ type, slot = null, rarity = "Common", name, stats = {}, flavor = "", weaponId = null, amount = 0 }) {
  return { id: makeId(type), type, slot, rarity, name, stats, flavor: flavor || choose(FLAVOR_LINES), weaponId, amount };
}

function weaponDisplayName(def, rarity) {
  const names = {
    greatsword: ["Two-Handed Apology", "Greatsword of Overcompensation", "Executive Cleaver"],
    hammer: ["Percussive Negotiator", "Hammer of Audience Retention", "Compliance Mallet"],
    spear: ["Personal Space Enforcer", "Spear of Plausible Distance", "Pointy Viewer Engagement Tool"],
    bow: ["Coward's Content Launcher", "Bow of Remote Consequences", "Sponsored String Dispenser"]
  };
  return `${rarity} ${choose(names[def.id] || [def.name])}`;
}

function generateWeaponItem(forceRare = false) {
  const weaponId = choose(WEAPON_ORDER.filter(id => id !== "fists"));
  const def = WEAPON_DEFINITIONS[weaponId];
  const rarity = rollRarity(forceRare);
  const p = rarityPower(rarity);
  return createItem({
    type: "weapon",
    slot: "weapon",
    rarity,
    weaponId,
    name: weaponDisplayName(def, rarity),
    stats: { damage: def.damage + p * 2, range: def.range, cooldown: def.cooldown, attack: Math.max(0, p - 1) },
    flavor: `A ${def.name.toLowerCase()} template with extra dungeon confidence sprayed on. Please face camera three before swinging.`
  });
}

function generateGear(forceRare = false) {
  const slot = choose(["body", "offhand", "trinket"]);
  const rarity = rollRarity(forceRare);
  const p = rarityPower(rarity);
  const base = slot === "body" ? choose(ARMOR_BASES) : slot === "offhand" ? choose(OFFHAND_BASES) : choose(TRINKET_BASES);
  const stats = { hp: 0, attack: 0, defense: 0, speed: 0, audience: 0 };
  if (slot === "body") { stats.hp = p * 10; stats.defense = Math.max(1, Math.floor(p / 2)); }
  if (slot === "offhand") { stats.defense = p; stats.hp = p * 3; }
  if (slot === "trinket") { Math.random() < 0.5 ? stats.attack = p * 2 : stats.audience = p * 3; }
  if (Math.random() < 0.24) stats.hp += p * 3;
  if (Math.random() < 0.20) stats.attack += p;
  if (Math.random() < 0.15) stats.speed += p * 0.03;
  return createItem({ type: slot === "trinket" ? "trinket" : "armor", slot, rarity, name: `${rarity} ${choose(ITEM_PREFIXES)} ${base}`, stats });
}

function generateJunkItem() {
  return createItem({ type: "junk", rarity: "Common", name: `${choose(ITEM_PREFIXES)} ${choose(JUNK_BASES)}`, flavor: "No stats. No resale value. Huge potential as a prop in your downfall." });
}

function generateLootBox(forceRare = false) { const rarity = rollRarity(forceRare); return { id: makeId("box"), type: "lootbox", rarity, name: `${rarity} Prize Box`, opened: false, flavor: "Can only be opened in a safe room. The dungeon calls this responsible dopamine handling.", stats: {} }; }
function generateGoldItem(amount) { return { id: makeId("gold"), type: "gold", rarity: "Common", name: `${amount} Gold`, amount, stats: {}, flavor: "Currency: the original jump scare." }; }

function itemTypeLabel(item) { if (!item) return "Unknown"; if (item.type === "gold") return "Gold"; if (item.type === "lootbox") return "Loot Box"; return item.slot ? SLOT_LABELS[item.slot] : item.type.charAt(0).toUpperCase() + item.type.slice(1); }
function itemDescription(i) {
  if (!i) return "";
  if (i.type === "gold") return `${i.amount} gold. It jingles with poor decision-making.`;
  if (i.type === "lootbox") return "Can only be opened in a safe room.";
  const s = getItemStats(i);
  const b = [];
  if (s.damage) b.push(`${s.damage} DMG`);
  if (s.range) b.push(`${s.range} RNG`);
  if (s.cooldown) b.push(`${s.cooldown} CD`);
  if (s.hp) b.push(`+${s.hp} HP`);
  if (s.attack) b.push(`+${s.attack} ATK`);
  if (s.defense) b.push(`+${s.defense} DEF`);
  if (s.speed) b.push(`+${s.speed.toFixed(2)} SPD`);
  if (s.audience) b.push(`+${s.audience} Audience`);
  return b.join(" · ") || "Mostly decorative. The dungeon approves of pointless confidence.";
}

function addItem(item) {
  player.inventory.push(item);
  if (item.type === "lootbox") { stats.lootBoxesFound++; achievement("NEW LOOT BOX", `You found a ${item.name}. It can only be opened in a safe room.`, `box_${item.id}`); }
  else if (item.type !== "junk") { stats.gearFound++; achievement("NEW GEAR", `You found ${item.name}. ${itemDescription(item)}`, `gear_${item.id}`); }
  updateInventoryUI(); updateHUD();
}

function getEquippedComparable(item) { return item?.slot ? player.equipment[item.slot] : null; }
function formatComparison(item) {
  if (!isEquippable(item)) return "";
  const equipped = getEquippedComparable(item);
  const next = getItemStats(item);
  const current = getItemStats(equipped);
  const rows = [];
  const keys = item.slot === "weapon" ? [["damage", "DMG"], ["range", "RNG"], ["cooldown", "CD", true], ["attack", "ATK"]] : [["hp", "HP"], ["attack", "ATK"], ["defense", "DEF"], ["speed", "SPD"], ["audience", "Audience"]];
  for (const [key, label, lowerIsBetter] of keys) {
    if (!next[key] && !current[key]) continue;
    const diff = (next[key] || 0) - (current[key] || 0);
    const good = lowerIsBetter ? diff < 0 : diff > 0;
    const bad = lowerIsBetter ? diff > 0 : diff < 0;
    const cls = good ? "statUp" : bad ? "statDown" : "statSame";
    const sign = diff > 0 ? "+" : "";
    const value = key === "speed" ? diff.toFixed(2) : diff;
    rows.push(`<div class="compareRow ${cls}"><span>${label}</span><span>${current[key] || 0} → ${next[key] || 0}</span><strong>${sign}${value}</strong></div>`);
  }
  return `<div class="compareBox"><div class="compareTitle">Against ${equipped ? escapeHtml(equipped.name) : `empty ${SLOT_LABELS[item.slot]} slot`}</div>${rows.join("") || "<div class=\"itemMeta\">No stat movement. Emotionally devastating.</div>"}</div>`;
}

function equipItem(id) {
  const idx = player.inventory.findIndex(i => i.id === id); if (idx < 0) return;
  const item = player.inventory[idx]; if (!isEquippable(item)) return;
  const old = player.equipment[item.slot];
  player.equipment[item.slot] = item;
  player.inventory.splice(idx, 1);
  if (old) player.inventory.push(old);
  if (item.slot === "weapon") setPlayerWeapon(item.weaponId || "fists", false);
  selectedInventoryItemId = old ? old.id : null;
  recalcEquipmentStats(); achievement("EQUIPPED", `You equipped ${item.name}. ${itemDescription(item)}`, `equip_${item.id}`); updateInventoryUI(); updateHUD();
}

function openLootBox(id) {
  const idx = player.inventory.findIndex(i => i.id === id); if (idx < 0) return; const box = player.inventory[idx]; if (box.type !== "lootbox") return;
  if (!player.safe) { announcer("Loot boxes may only be opened in safe rooms. The dungeon believes in responsible dopamine distribution."); return; }
  player.inventory.splice(idx, 1); stats.lootBoxesOpened++; const coins = 8 + Math.floor(Math.random() * 16) + rarityPower(box.rarity) * 6; player.coins += coins;
  const gear = Math.random() < 0.42 ? generateWeaponItem(box.rarity === "Rare" || box.rarity === "Epic" || box.rarity === "Legendary") : generateGear(box.rarity === "Rare" || box.rarity === "Epic" || box.rarity === "Legendary");
  player.inventory.push(gear); stats.gearFound++;
  achievement("LOOT BOX OPENED", `You opened ${box.name} and received ${coins} gold and ${gear.name}. Pants-based civilization remains possible.`, `open_${box.id}`);
  if (!achievements.has("firstLootBoxOpen")) achievement("NEW ACHIEVEMENT: Delayed Gratification", "You waited until a safe room to open a box. Somewhere, an impulse-control researcher just shed a single tear.", "firstLootBoxOpen");
  updateInventoryUI(); updateHUD();
}
function discardItem(id) { const idx = player.inventory.findIndex(i => i.id === id); if (idx < 0) return; const [item] = player.inventory.splice(idx, 1); if (selectedInventoryItemId === id) selectedInventoryItemId = null; announcer(`You dropped ${item.name}. The dungeon has sold it to someone with lower standards.`); updateInventoryUI(); updateHUD(); }
function recalcEquipmentStats() {
  let hp = 0, atk = 0, spd = 0, def = 0, aud = 0;
  for (const item of Object.values(player.equipment)) { if (!item) continue; const s = getItemStats(item); hp += s.hp || item.hp || 0; atk += s.attack || item.attack || 0; spd += s.speed || item.speed || 0; def += s.defense || item.defense || 0; aud += s.audience || item.audience || 0; }
  const old = player.maxHp; player.maxHp = 100 + (player.level - 1) * 14 + hp; player.attackDamage = 20 + (player.level - 1) * 4 + atk; player.speed = player.baseSpeed + spd; player.defense = def; player.audienceBonus = aud; if (player.maxHp > old) player.hp += player.maxHp - old; player.hp = Math.min(player.hp, player.maxHp);
}
function lootBoxCount() { return player.inventory.filter(i => i.type === "lootbox").length; }

function renderEquipmentStats() {
  const weapon = getCurrentWeapon();
  return `<div class="crawlerStats"><div><b>LV</b> ${player.level}</div><div><b>Gold</b> ${player.coins}</div><div><b>HP</b> ${Math.floor(player.hp)}/${player.maxHp}</div><div><b>ATK</b> ${player.attackDamage}</div><div><b>Weapon</b> ${escapeHtml(weapon.name)}</div></div><div class="equipSlots">${Object.keys(SLOT_LABELS).map(s => { const item = player.equipment[s]; return `<div class="equipSlot rarity-${item?.rarity || "Empty"}"><span>${SLOT_LABELS[s]}</span><strong>${item ? escapeHtml(item.name) : "Empty"}</strong></div>`; }).join("")}</div><div class="itemMeta">DEF ${player.defense} · SPD ${player.speed.toFixed(2)} · Audience Bonus ${player.audienceBonus}</div>`;
}
function renderInventoryCard(item) {
  return `<button class="invCard rarity-${item.rarity || "Common"} ${selectedInventoryItemId === item.id ? "selected" : ""}" onclick="selectInventoryItem('${item.id}')"><span class="itemName">${escapeHtml(item.name)}</span><span class="itemMeta">${escapeHtml(itemTypeLabel(item))} · ${escapeHtml(item.rarity || "Common")}</span><span class="itemStats">${escapeHtml(itemDescription(item))}</span></button>`;
}
function renderSelectedItem(item) {
  if (!item) return `<div class="itemDetail empty">Select loot to receive unsolicited opinions from the dungeon.</div>`;
  const actions = [];
  if (isEquippable(item)) actions.push(`<button class="itemBtn primary" onclick="equipItem('${item.id}')">Equip</button>`);
  if (item.type === "lootbox") actions.push(`<button class="itemBtn primary" onclick="openLootBox('${item.id}')">Open</button>`);
  actions.push(`<button class="itemBtn danger" onclick="discardItem('${item.id}')">Drop</button><button class="itemBtn" onclick="clearInventorySelection()">Close</button>`);
  return `<div class="itemDetail rarity-${item.rarity || "Common"}"><div class="itemName">${escapeHtml(item.name)}</div><div class="itemMeta">${escapeHtml(itemTypeLabel(item))} · ${escapeHtml(item.rarity || "Common")}</div><p>${escapeHtml(item.flavor || choose(FLAVOR_LINES))}</p><div class="itemMeta">${escapeHtml(itemDescription(item))}</div>${formatComparison(item)}<div class="itemActions">${actions.join("")}</div></div>`;
}
function selectInventoryItem(id) { selectedInventoryItemId = id; updateInventoryUI(); }
function clearInventorySelection() { selectedInventoryItemId = null; updateInventoryUI(); }
function updateInventoryUI() {
  const panel = document.getElementById("inventoryPanel"); if (!panel) return;
  const eq = document.getElementById("equipmentStats"), list = document.getElementById("inventoryList"), detail = document.getElementById("inventoryDetail");
  if (eq) eq.innerHTML = renderEquipmentStats();
  const selected = player.inventory.find(i => i.id === selectedInventoryItemId);
  if (detail) detail.innerHTML = renderSelectedItem(selected);
  if (!list) return;
  if (!player.inventory.length) { list.innerHTML = '<div class="invEmpty">Inventory empty. The dungeon recommends tasteful grave robbery.</div>'; return; }
  list.innerHTML = player.inventory.map(renderInventoryCard).join("");
}
function toggleInventoryPanel() { const p = document.getElementById("inventoryPanel"), l = document.getElementById("logPanel"), r = document.getElementById("safeRoomRecap"), loot = document.getElementById("lootPanel"); if (!p) return; if (p.style.display === "block") { p.style.display = "none"; return; } if (l) l.style.display = "none"; if (r) r.style.display = "none"; if (loot) loot.style.display = "none"; updateInventoryUI(); p.style.display = "block"; }
function closeInventoryPanel() { const p = document.getElementById("inventoryPanel"); if (p) p.style.display = "none"; }

function getCorpseById(id) { return corpses.find(c => c.id === id); }
function openCorpseLoot(corpse) { if (!corpse || corpse.looted) return; activeLootCorpseId = corpse.id; const inv = document.getElementById("inventoryPanel"), log = document.getElementById("logPanel"), recap = document.getElementById("safeRoomRecap"); if (inv) inv.style.display = "none"; if (log) log.style.display = "none"; if (recap) recap.style.display = "none"; updateLootPanel(); const panel = document.getElementById("lootPanel"); if (panel) panel.style.display = "block"; }
function closeLootPanel() { const panel = document.getElementById("lootPanel"); if (panel) panel.style.display = "none"; activeLootCorpseId = null; }
function takeCorpseItem(itemId) { const corpse = getCorpseById(activeLootCorpseId); if (!corpse || corpse.looted) return; const idx = corpse.loot.findIndex(i => i.id === itemId); if (idx < 0) return; const [item] = corpse.loot.splice(idx, 1); grantLootItem(item, corpse); finalizeCorpseIfEmpty(corpse); updateLootPanel(); updateInventoryUI(); updateHUD(); }
function takeAllCorpseLoot() { const corpse = getCorpseById(activeLootCorpseId); if (!corpse || corpse.looted) return; const items = corpse.loot.splice(0); for (const item of items) grantLootItem(item, corpse); finalizeCorpseIfEmpty(corpse); updateLootPanel(); updateInventoryUI(); updateHUD(); }
function grantLootItem(item, corpse) { if (item.type === "gold") player.coins += item.amount; else { player.inventory.push(item); if (item.type === "lootbox") stats.lootBoxesFound++; if (isEquippable(item)) stats.gearFound++; } changeAudience(corpse?.boss ? 2 : 1); }
function finalizeCorpseIfEmpty(corpse) { if (corpse.loot.length) return; corpse.looted = true; achievement(corpse.boss ? "BOSS CORPSE STRIPPED" : "CORPSE STRIPPED", `You emptied ${corpse.name}. The dungeon thanks you for keeping the arena tidy and emotionally awful.`, `loot_${corpse.id}`); closeLootPanel(); }
function updateLootPanel() {
  const panel = document.getElementById("lootPanel"); if (!panel) return;
  const corpse = getCorpseById(activeLootCorpseId);
  const title = document.getElementById("lootTitle"), grid = document.getElementById("corpseLootGrid"), empty = document.getElementById("lootEmpty");
  if (!corpse) { closeLootPanel(); return; }
  if (title) title.textContent = corpse.name;
  if (empty) empty.style.display = corpse.loot.length ? "none" : "block";
  if (grid) grid.innerHTML = corpse.loot.map(item => `<div class="lootCard rarity-${item.rarity || "Common"}"><div class="itemName">${escapeHtml(item.name)}</div><div class="itemMeta">${escapeHtml(itemTypeLabel(item))}</div><div class="itemStats">${escapeHtml(itemDescription(item))}</div><button class="itemBtn primary" onclick="takeCorpseItem('${item.id}')">Take</button></div>`).join("");
}

function rewardChestLoot() {
  const roll = Math.random();
  if (roll < .36) { const gained = 5 + Math.floor(Math.random() * 12); player.coins += gained; achievement("CHEST LOOT", `You found ${gained} gold. The dungeon reminds you that wealth is not a personality, but it helps.`, `coins_${Date.now()}_${Math.random()}`); }
  else if (roll < .66) addItem(generateLootBox());
  else if (roll < .84) addItem(generateWeaponItem());
  else addItem(generateGear());
  if (!achievements.has("firstWearableLoot") && stats.gearFound > 0) achievement("NEW ACHIEVEMENT: Pants Adjacent", "You found wearable equipment. Whether this improves your dignity remains under review.", "firstWearableLoot");
  updateInventoryUI(); updateHUD();
}

function gainXP(amount) {
  player.xp += amount;

  if (!achievements.has("firstXP")) {
    achievement("NEW ACHIEVEMENT: Number Goes Up", "You gained experience. This is how games trick mammals into enjoying chores.", "firstXP");
  }

  while (player.xp >= player.xpToNext) {
    player.xp -= player.xpToNext;
    levelUpPlayer();
  }

  updateHUD();
}

function levelUpPlayer() {
  player.level++;
  player.xpToNext = Math.floor(40 + player.level * 28);
  recalcEquipmentStats();
  player.hp = player.maxHp;

  changeAudience(6);
  achievement("LEVEL UP", `You reached level ${player.level}. Your numbers improved, which is technically character development.`, `level${player.level}`);
}


function changeAudience(amount) {
  audienceScore = Math.max(0, Math.min(100, audienceScore + amount));
  updateHUD();
  if (audienceScore >= 25 && !achievements.has("audience25")) achievement("NEW ACHIEVEMENT: Mildly Watchable", "Your audience score reached 25. Somewhere, a bored alien looked up from its sandwich.", "audience25");
  if (audienceScore >= 50 && !achievements.has("audience50")) achievement("NEW ACHIEVEMENT: Content Creature", "Your audience score reached 50. You are no longer background noise. Terrifying progress.", "audience50");
}

function updateReputation() {
  const safeSeconds = Math.floor(stats.timeInSafeRoomFrames / 60);
  const outsideSeconds = Math.floor(stats.timeOutsideSafeRoomFrames / 60);
  const c = [];
  if (roomsSeen >= 15 && stats.chestsOpened <= 1) c.push("Dungeon Tourist");
  if (stats.chestsOpened >= 2 && stats.chestsOpened >= stats.enemiesKilled + 1) c.push("Loot Goblin");
  if (stats.doorsOpened >= 4 && stats.enemiesKilled <= 1) c.push("Door Enthusiast");
  if (stats.enemiesKilled >= 2 && stats.enemiesKilled >= stats.chestsOpened) c.push("Murder Hobo Intern");
  if (safeSeconds > outsideSeconds && outsideSeconds > 10) c.push("Strategic Coward");
  if (stats.missedAttacks >= 5) c.push("Air Boxer");
  if (stats.wallBumps >= 12) c.push("Wall Conversationalist");
  if (stats.damageTaken >= 24 && stats.enemiesKilled >= 1) c.push("Damage Sponge");
  if (audienceScore >= 35 && stats.riskyMoments >= 3) c.push("Ratings Goblin");
  currentReputation = c[0] || "Undeclared Menace";
  return currentReputation;
}

function getReputationComment(rep) {
  return {
    "Dungeon Tourist": "You are sightseeing under conditions most travel agents would describe as legally indefensible.",
    "Loot Goblin": "You prioritize treasure over safety, dignity, and basic pattern recognition.",
    "Door Enthusiast": "You have formed a suspicious emotional attachment to doors.",
    "Murder Hobo Intern": "You are not yet a full murder hobo, but your resume has promise.",
    "Strategic Coward": "Cowardice is such an ugly word. We prefer 'resource-conserving mammal.'",
    "Air Boxer": "Your rivalry with empty space continues to define your brand.",
    "Wall Conversationalist": "The walls know your face better than your allies do.",
    "Damage Sponge": "You absorb punishment with the confidence of someone who has misunderstood the assignment.",
    "Ratings Goblin": "You are becoming entertaining in the worst possible way.",
    "Undeclared Menace": "Your brand remains unclear. Try committing to a bit before you die."
  }[rep] || "Your brand remains unclear. Try committing to a bit before you die.";
}
